# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo7', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintableElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('positionX', models.FloatField()),
                ('positionY', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
            ],
        ),
    ]
