# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo7', '0002_printableelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='printableelement',
            name='reportTemplate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='demo7.ReportTemplate'),
            preserve_default=False,
        ),
    ]
