# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo7', '0004_auto_20171025_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateelement',
            name='nodeClass',
        ),
        migrations.AddField(
            model_name='templateelement',
            name='html',
            field=models.TextField(default=None),
        ),
    ]
