# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo7', '0008_auto_20171027_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateelement',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templateelement',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
