# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo7', '0009_auto_20171027_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateelement',
            old_name='parameters',
            new_name='filterConditions',
        ),
    ]
