# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo7', '0010_auto_20171028_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateelement',
            name='columns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='modelName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
