# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_id', models.CharField(max_length=2)),
                ('lang_dc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_li_id', models.CharField(max_length=10)),
                ('nav_li_dc', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsite.Language')),
            ],
        ),
    ]
