# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang_id',
            field=models.CharField(max_length=5),
        ),
    ]
