# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChargeableQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('converting_factor', models.FloatField(blank=True, null=True)),
                ('comparison', models.CharField(blank=True, choices=[('min', 'Minimum'), ('max', 'Maximum')], max_length=3, null=True)),
                ('target', models.IntegerField()),
                ('base', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('register_number', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.Company')),
                ('data_sheet', models.ManyToManyField(to='horizon.DataSheet')),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('element', models.ManyToManyField(to='horizon.Element')),
                ('related_geo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horizon.Geo')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.Element')),
            ],
        ),
        migrations.CreateModel(
            name='PriceCondition',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('low', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PriceSheet',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('chargeable_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.ChargeableQuantity')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.Element')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingOption',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('setting', models.ManyToManyField(to='horizon.Setting')),
            ],
        ),
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('long_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='quantity',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.UoM'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.PriceCondition'),
        ),
        migrations.AddField(
            model_name='element',
            name='price_sheet',
            field=models.ManyToManyField(to='horizon.PriceSheet'),
        ),
        migrations.AddField(
            model_name='cost',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.Element'),
        ),
        migrations.AddField(
            model_name='cost',
            name='price_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.PriceCondition'),
        ),
        migrations.AddField(
            model_name='chargeablequantity',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.UoM'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ManyToManyField(to='horizon.Company'),
        ),
        migrations.AddField(
            model_name='category',
            name='related_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.Category'),
        ),
    ]
