# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pid', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pid', models.CharField(max_length=6)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.DataType')),
                ('rgeo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horizon.Geo')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seq', models.IntegerField(blank=True)),
                ('geo', models.ManyToManyField(to='horizon.Geo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.DataType')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.DataType')),
            ],
        ),
    ]
