# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horizon.Category'),
        ),
    ]
