# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0002_auto_20161218_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSetting',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('values', models.CharField(max_length=255)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='horizon.Board')),
                ('settings', models.ManyToManyField(to='horizon.Setting')),
            ],
        ),
        migrations.RemoveField(
            model_name='chargeablequantity',
            name='base',
        ),
        migrations.RemoveField(
            model_name='chargeablequantity',
            name='target',
        ),
        migrations.RemoveField(
            model_name='chargeablequantity',
            name='uom',
        ),
        migrations.AddField(
            model_name='quantity',
            name='role',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
