# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0004_auto_20161218_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizon',
            name='owner',
            field=models.ManyToManyField(to='horizon.HorizonUser'),
        ),
    ]
