# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0005_auto_20161218_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
