# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0006_setting_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardSetting',
            new_name='HorizonSetting',
        ),
    ]
