# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0007_auto_20161218_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='company',
            new_name='companies',
        ),
        migrations.RenameField(
            model_name='geo',
            old_name='element',
            new_name='elements',
        ),
        migrations.RenameField(
            model_name='horizon',
            old_name='owner',
            new_name='owners',
        ),
        migrations.RenameField(
            model_name='settingoption',
            old_name='setting',
            new_name='settings',
        ),
        migrations.RemoveField(
            model_name='element',
            name='data_sheet',
        ),
        migrations.RemoveField(
            model_name='element',
            name='price_sheet',
        ),
        migrations.AddField(
            model_name='datasheet',
            name='elements',
            field=models.ManyToManyField(to='horizon.Element'),
        ),
        migrations.AddField(
            model_name='pricesheet',
            name='elements',
            field=models.ManyToManyField(to='horizon.Element'),
        ),
    ]
