# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0008_auto_20161225_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='companies',
        ),
    ]
