# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0009_remove_category_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geo',
            name='elements',
        ),
        migrations.AddField(
            model_name='element',
            name='locations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
