# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0010_auto_20161225_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='QESetting',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('values', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Horizon',
            new_name='QE',
        ),
        migrations.RenameModel(
            old_name='HorizonUser',
            new_name='QEUser',
        ),
        migrations.RemoveField(
            model_name='horizonsetting',
            name='horizon',
        ),
        migrations.RemoveField(
            model_name='horizonsetting',
            name='settings',
        ),
        migrations.DeleteModel(
            name='HorizonSetting',
        ),
        migrations.AddField(
            model_name='qesetting',
            name='qe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='horizon.QE'),
        ),
        migrations.AddField(
            model_name='qesetting',
            name='settings',
            field=models.ManyToManyField(to='horizon.Setting'),
        ),
    ]
