# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0011_auto_20161227_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QEUser',
            new_name='DawnUser',
        ),
        migrations.RenameModel(
            old_name='QE',
            new_name='PlatformDawn',
        ),
    ]
