# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0012_auto_20161229_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QESetting',
            new_name='DawnSetting',
        ),
        migrations.RenameField(
            model_name='dawnsetting',
            old_name='qe',
            new_name='platform_dawn',
        ),
        migrations.AddField(
            model_name='dawnuser',
            name='permissions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='geos',
            field=models.ManyToManyField(to='horizon.Geo'),
        ),
    ]
