# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0013_auto_20161229_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='geos',
        ),
    ]
