# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0014_remove_element_geos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.Element')),
            ],
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='element',
        ),
        migrations.AddField(
            model_name='quantity',
            name='data_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horizon.DataElement'),
            preserve_default=False,
        ),
    ]
