# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0015_auto_20161229_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='chargeable_quantity',
        ),
        migrations.AddField(
            model_name='quantity',
            name='comparison',
            field=models.CharField(blank=True, choices=[('min', 'Minimum'), ('max', 'Maximum')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='quantity',
            name='converting_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ChargeableQuantity',
        ),
    ]
