# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0016_auto_20161229_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheet',
            name='elements',
        ),
        migrations.AddField(
            model_name='datasheet',
            name='data_elements',
            field=models.ManyToManyField(to='horizon.DataElement'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horizon.UoM'),
        ),
    ]
