# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0017_auto_20161229_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlatformDawn',
            new_name='Scheme',
        ),
        migrations.RenameModel(
            old_name='DawnSetting',
            new_name='SchemeSetting',
        ),
        migrations.AlterField(
            model_name='quantity',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
