# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0018_auto_20161230_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='dawnuser',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='horizon.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='code_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
