# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0019_auto_20170121_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dawnuser',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ManyToManyField(to='horizon.DawnUser'),
        ),
    ]
