# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0020_auto_20170121_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='user',
            new_name='owners',
        ),
    ]
