# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0021_auto_20170121_0536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DawnUser',
            new_name='HorizonUser',
        ),
    ]
