# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0022_auto_20170122_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemesetting',
            old_name='platform_dawn',
            new_name='scheme',
        ),
        migrations.RenameField(
            model_name='schemesetting',
            old_name='values',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='schemesetting',
            name='settings',
        ),
        migrations.AddField(
            model_name='schemesetting',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horizon.Setting'),
            preserve_default=False,
        ),
    ]
