# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0023_auto_20170122_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemesetting',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.Scheme'),
        ),
    ]
