# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0024_auto_20170122_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemesetting',
            options={'ordering': ['pid']},
        ),
    ]
