# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0025_auto_20170128_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='setting_locked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
