# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0026_scheme_setting_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='scheme',
            field=models.OneToOneField(default=900000001, on_delete=django.db.models.deletion.CASCADE, to='horizon.Scheme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricesheet',
            name='scheme',
            field=models.ForeignKey(default=900000001, on_delete=django.db.models.deletion.CASCADE, to='horizon.Scheme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quantity',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horizon.UoM'),
        ),
    ]
