# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0029_auto_20170206_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasheetsetting',
            options={'ordering': ['pid']},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'ordering': ['pid']},
        ),
        migrations.AlterModelOptions(
            name='schemesetting',
            options={'ordering': ['pid']},
        ),
        migrations.AddField(
            model_name='datasheet',
            name='uom',
            field=models.ForeignKey(default=8599, on_delete=django.db.models.deletion.CASCADE, to='horizon.UoM'),
            preserve_default=False,
        ),
    ]
