# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0030_auto_20170213_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheet',
            name='uom',
        ),
        migrations.AddField(
            model_name='datasheet',
            name='uom',
            field=models.ManyToManyField(to='horizon.UoM'),
        ),
    ]
