# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0032_auto_20170213_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('class_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='geo',
            options={'verbose_name': 'Geography'},
        ),
    ]
