# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0033_auto_20170214_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='flatten',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasheet',
            name='data_fields',
            field=models.ManyToManyField(to='horizon.DataField'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
