# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0034_auto_20170214_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafield',
            old_name='class_name',
            new_name='model_name',
        ),
    ]
