# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0035_auto_20170214_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheetField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('data_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.DataField')),
                ('data_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.DataSheet')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dataelement',
            options={'ordering': ['pid']},
        ),
    ]
