# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0038_auto_20170215_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasheet',
            options={'ordering': ['pid']},
        ),
    ]
