# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0039_auto_20170215_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='through',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
