# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0040_datafield_through'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('from', 'From'), ('to', 'To'), ('via', 'Via'), ('at', 'At')], max_length=4)),
                ('sequence', models.IntegerField(default=0)),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.Geo')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='PriceSheetElement',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.Element')),
            ],
        ),
        migrations.RenameModel(
            old_name='DataElement',
            new_name='DataSheetElement',
        ),
        migrations.RenameField(
            model_name='datasheet',
            old_name='data_elements',
            new_name='data_sheet_elements',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='data_element',
            new_name='data_sheet_element',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='element',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='price_condition',
        ),
        migrations.RemoveField(
            model_name='price',
            name='element',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_condition',
        ),
        migrations.RemoveField(
            model_name='settingoption',
            name='settings',
        ),
        migrations.AddField(
            model_name='company',
            name='categories',
            field=models.ManyToManyField(to='horizon.Category'),
        ),
        migrations.AddField(
            model_name='cost',
            name='data_sheet_element',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='horizon.DataSheetElement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cost',
            name='total',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='price_conditions',
            field=models.ManyToManyField(to='horizon.PriceCondition'),
        ),
        migrations.AddField(
            model_name='pricecondition',
            name='uom',
            field=models.ForeignKey(default=8599, on_delete=django.db.models.deletion.CASCADE, to='horizon.UoM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='setting_options',
            field=models.ManyToManyField(to='horizon.SettingOption'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_sheet_element',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='horizon.PriceSheetElement'),
            preserve_default=False,
        ),
    ]
