# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0041_auto_20170219_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='locations',
        ),
        migrations.AddField(
            model_name='element',
            name='locations',
            field=models.ManyToManyField(to='horizon.Location'),
        ),
    ]
