# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0042_auto_20170219_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='attribute_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
