# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0044_auto_20170219_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheet',
            name='uoms',
        ),
        migrations.AddField(
            model_name='setting',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
