# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0048_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(default=3004, on_delete=django.db.models.deletion.CASCADE, to='horizon.Currency'),
            preserve_default=False,
        ),
    ]
