# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0049_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSheetField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('price_conditions', models.ManyToManyField(to='horizon.PriceCondition')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.RenameModel(
            old_name='DataField',
            new_name='DisplayField',
        ),
        migrations.AddField(
            model_name='pricesheetfield',
            name='price_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.DisplayField'),
        ),
        migrations.AddField(
            model_name='pricesheetfield',
            name='price_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.PriceSheet'),
        ),
    ]
