# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0052_auto_20170519_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='company',
        ),
        migrations.AddField(
            model_name='datasheetelement',
            name='vendor',
            field=models.ForeignKey(default=67000001, on_delete=django.db.models.deletion.CASCADE, to='horizon.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricesheetelement',
            name='vendor',
            field=models.ForeignKey(default=67000001, on_delete=django.db.models.deletion.CASCADE, to='horizon.Company'),
            preserve_default=False,
        ),
    ]
