# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0053_auto_20170519_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorizonSetting',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pricesheetfield',
            name='display_field',
        ),
        migrations.DeleteModel(
            name='DisplayField',
        ),
    ]
