# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0054_auto_20170521_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizonuser',
            name='default_language',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
