# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0055_horizonuser_default_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='category',
        ),
        migrations.AddField(
            model_name='datasheetelement',
            name='category',
            field=models.ForeignKey(default=67061, on_delete=django.db.models.deletion.CASCADE, to='horizon.Category'),
            preserve_default=False,
        ),
    ]
