# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0058_auto_20170522_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='uom',
            field=models.ForeignKey(default=8501, on_delete=django.db.models.deletion.CASCADE, to='horizon.UoM'),
            preserve_default=False,
        ),
    ]
