# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0061_auto_20170530_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='sequence',
            field=models.IntegerField(),
        ),
    ]
