# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0062_auto_20170530_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
