# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0065_auto_20170601_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricesheet',
            name='number_of_fields',
        ),
        migrations.AddField(
            model_name='datasheet',
            name='number_of_price_fields',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
