# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0066_auto_20170601_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricecondition',
            old_name='common_name',
            new_name='display_name',
        ),
    ]
