# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0067_auto_20170601_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['pid']},
        ),
        migrations.RemoveField(
            model_name='pricesheet',
            name='scheme',
        ),
        migrations.AddField(
            model_name='pricesheet',
            name='vendor',
            field=models.ForeignKey(default=6701, on_delete=django.db.models.deletion.CASCADE, to='horizon.Company'),
            preserve_default=False,
        ),
    ]
