# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0068_auto_20170602_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.ForeignKey(default=67004, on_delete=django.db.models.deletion.CASCADE, to='horizon.Category'),
            preserve_default=False,
        ),
    ]
