# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0069_price_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecondition',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
