# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0070_pricecondition_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizonuser',
            name='company',
            field=models.ForeignKey(default=6707, on_delete=django.db.models.deletion.CASCADE, to='horizon.Company'),
        ),
    ]
