# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0073_datasheet_setting_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='cost',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='currency',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='datasheetelement',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='datasheetsetting',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='element',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='geo',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='price',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='pricecondition',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='pricesheet',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='pricesheetelement',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='scheme',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='schemesetting',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='settingoption',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='uom',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
