# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0075_horizonsetting_hash_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizonuser',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='horizonuser',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
