# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0076_auto_20170624_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='horizonuser',
            options={'ordering': ['pid']},
        ),
        migrations.AddField(
            model_name='quantity',
            name='hash_pid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='quantity',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
