# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0077_auto_20170702_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='id',
        ),
        migrations.AlterField(
            model_name='quantity',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
