# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0078_auto_20170702_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorizonDate',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('hash_pid', models.CharField(default='0', max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='datasheetelement',
            name='dates',
            field=models.ManyToManyField(to='horizon.HorizonDate'),
        ),
    ]
