# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0079_auto_20170702_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('hash_pid', models.CharField(default='0', max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('sequence', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='HorizonDate',
        ),
        migrations.AlterField(
            model_name='datasheetelement',
            name='dates',
            field=models.ManyToManyField(to='horizon.Date'),
        ),
    ]
