# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0080_auto_20170702_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDate',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('hash_pid', models.CharField(default='0', max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('sequence', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='datasheetelement',
            name='dates',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.AddField(
            model_name='datadate',
            name='data_sheet_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.DataSheetElement'),
        ),
    ]
