# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0081_auto_20170702_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='datasheetelement',
            name='start_date',
        ),
    ]
