# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0082_auto_20170702_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemesetting',
            name='locked',
        ),
    ]
