# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0084_auto_20170704_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadate',
            old_name='data_sheet_element',
            new_name='datasheet_element',
        ),
        migrations.RenameField(
            model_name='datasheet',
            old_name='data_sheet_elements',
            new_name='datasheet_elements',
        ),
        migrations.RenameField(
            model_name='datasheetfield',
            old_name='data_sheet',
            new_name='datasheet',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='data_sheet_element',
            new_name='datasheet_element',
        ),
    ]
