# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0085_auto_20170709_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='number_of_price_fields',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
