# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0087_datasheet_datasheet_template_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheet',
            old_name='datasheet_template_created',
            new_name='xl_template_created',
        ),
    ]
