# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0089_auto_20170718_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='xltemplate_file_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
