# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0090_datasheet_xltemplate_file_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheet',
            old_name='xltemplate_file_location',
            new_name='xltemplate_filelink',
        ),
    ]
