# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0092_auto_20170719_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='xltemplate_file_fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
