# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0093_datasheet_xltemplate_file_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='geo',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='setting_options',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='SettingOption',
        ),
    ]
