# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0095_auto_20170724_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheetelement',
            name='category',
        ),
        migrations.AddField(
            model_name='datasheet',
            name='category',
            field=models.ForeignKey(default=67004, on_delete=django.db.models.deletion.CASCADE, to='horizon.Category'),
        ),
    ]
