# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0097_setting_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='xldatasheet_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
