# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0101_auto_20170902_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.Category'),
        ),
    ]
