# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0102_auto_20170902_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
