# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0103_auto_20170902_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='register_number',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
