# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0104_auto_20170902_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='data_locked',
            field=models.BooleanField(default=False),
        ),
    ]
