# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0106_auto_20170908_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['pid']},
        ),
        migrations.RenameField(
            model_name='datasheetfield',
            old_name='quantity_type',
            new_name='quantity_role',
        ),
        migrations.AlterField(
            model_name='location',
            name='datasheet_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horizon.DataSheetElement'),
        ),
    ]
