# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0107_auto_20170925_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheet',
            name='datasheet_elements',
        ),
    ]
